<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MeshAI.Demo\**" />
    <Compile Remove="MeshAI.Tests\**" />
    <EmbeddedResource Remove="MeshAI.Demo\**" />
    <EmbeddedResource Remove="MeshAI.Tests\**" />
    <None Remove="MeshAI.Demo\**" />
    <None Remove="MeshAI.Tests\**" />
  </ItemGroup>

</Project>
